version: '3.6'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.8.2
  INSTALL_NODE_VERSION: 12

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules
    - ./dev.db:/tmp/dev.db

services:
  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "airscore-development"
    container_name: flask_dev
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
      - "2992:2992"
    environment:
      REDIS_URL: ${REDIS_CONTAINER}://${REDIS_CONTAINER}:6379
      REDIS_CONTAINER: ${REDIS_CONTAINER}
      WEB_SERVER_CONTAINER: ${WEB_SERVER_CONTAINER}
      FLASK_CONTAINER: flask_dev
      FLASK_PORT: ${FLASK_PORT}
      FLASK_DEBUG: 1
    <<: *default_volumes

  manage:
    build:
      context: .
      target: manage
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "airscore-manage"
    container_name: manage
    stdin_open: true
    tty: true
    <<: *default_volumes

  redis:
    image: redis
    container_name: ${REDIS_CONTAINER}

volumes:
  node-modules:
  static-build:
  dev-db:
